# Generated by Django 5.0.2 on 2024-02-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_post_image_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
